name: Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.7
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Unit tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: github.com/multiversx/mx-chain-keys-monitor-go
